## 00. Pytorch Fundamentals

Notebook resource:https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating a Tensor

In [ ]:
#Scalar
scalar=torch.Tensor(7)

In [ ]:
scalar

tensor([ 1.1225e-10,  4.4997e-41,  1.0634e+37,  3.1866e+36,  3.8026e-41,
         0.0000e+00, -1.0842e-19])

In [ ]:
scalar.ndim

1

In [ ]:
#Vector
vector=torch.Tensor([7,7])
vector

tensor([7., 7.])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
matrix=torch.Tensor([[1,2,3],
                    [2,3,4]])
matrix

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [ ]:
matrix.shape

torch.Size([2, 3])

In [ ]:
#Tensors
tensor=torch.Tensor([[[1,2,3],
                      [3,6,9],
                     [2,4,6]]])
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 6.]]])

### Random Tensors

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust these random numbers to better represent the data.

Start with random numbers-->look at the data -->update the random numbers-->look at data-->update the random nummbers

torch.rand:https://pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

In [ ]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.6049, 0.4617, 0.6131, 0.3012],
        [0.9208, 0.6514, 0.2256, 0.2111],
        [0.2974, 0.6854, 0.0604, 0.2545]])

In [ ]:
#Create a random tensor with image similar to shape an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) #colour channels(RGB),height,width
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### zeros and ones

In [ ]:
#Create a tensor of all zeros
zero=torch.zeros(size=(3,4))
#Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones,zero

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors-like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor_datatypes
**Note**: Tensor datatypes is one of the three big issues with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:

#Float 32 Tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#Create a tensor
some_tensor=torch.rand(3,4)
some_tensor
#find out details about some Tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.2556, 0.8327, 0.7066, 0.4298],
        [0.5166, 0.7964, 0.8351, 0.7735],
        [0.6475, 0.7692, 0.9507, 0.3586]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors(tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [ ]:
#Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor=tensor*10

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
#Subtract 10
tensor-10

tensor([ 0, 10, 20])

In [ ]:
#Try out PyTorch in-built function
torch.mul(tensor,10)
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise Multiplication
2. Matrix Multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimmensions** must match:
* `(3,2)@(3,2)` won't work
* `(2,3)@(3,2)` will work

2. The resulting matrix has the shape of the **outer dimmensions**:
* `(2,3)@(3,2)`-->`(2,2)`
* `(3,2)@(2,3)`-->`(3,3)`

In [ ]:
# Element wise Multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals:tensor([100, 400, 900])


In [ ]:
#Multiplication Multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(1400)
CPU times: user 1.69 ms, sys: 0 ns, total: 1.69 ms
Wall time: 1.81 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 298 µs, sys: 870 µs, total: 1.17 ms
Wall time: 1.03 ms


tensor(1400)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6721, 1.0202, 1.1910],
        [0.5952, 0.9745, 1.1620],
        [0.3170, 0.4052, 0.4471]])

### Finding the min, max and sum of the tensors(tensor aggregation)

In [ ]:
#Create a tensor
X=torch.arange(0,100,10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the man
X.min(),torch.min(X)

(tensor(0), tensor(0))

In [ ]:
#Find the max
X.max(),torch.max(X)

(tensor(90), tensor(90))

In [ ]:
#Find the mean
torch.mean(X.type(torch.float32)),X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(X),X.sum()

(tensor(450), tensor(450))

### Finding the positional min() and max()

In [ ]:
#Find the position in the tensor that has minimum value
X.argmin(),torch.argmin(X)

(tensor(0), tensor(0))

In [ ]:
#find the position in the tensor that has a maximum value
X.argmax(),torch.argmax(X)

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing
* Reshaping- reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking- combine multiple tensors on top of each other
* Squeeze - removes all `1` dimensions from a tensor
* Unsqeeze- add a `1` dimension to a target tensor
* Premute - return a view of the input with dimensions premuted(swapped) in a certain way


In [ ]:
#let's create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes X(because a view of a tensor share the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze()- removes all single dimensions from a target tensor
X=torch.zeros(2,1,2,1,2)
X.size()
y=torch.squeeze(X)
y.size()
y=torch.squeeze(X,0)
y.size()
y=torch.squeeze(X,1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed=x_reshaped.squeeze()
x_squeezed.shape

torch.Size([9])

In [ ]:
print(f"Previous tensor:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")
#Add on an extra dimension with unsqueeze
X_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{X_unsqueezed}")
print(f"New shape:{X_unsqueezed.shape}")

Previous tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [ ]:
#torch.permute- rearranges the dimensions of a target tensor in a specified order
X_original=torch.rand(size=(224,224,3))#[heigth,width,colour_channels]
#permute the original tensor to rearrange the axis(or dim) order
X_permuted=X_original.permute(2,0,1)#shifts axis 0-->1,1-->2,2-->0
print(f"Previous shape:{X_original.shape}")
print(f"New shape:{X_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


### Indexing(Selecting data from tensors)
Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensor
x[0][0]
#let's index on the most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [ ]:
#You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of 0th and 1st dimension but only index of 1st of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all the values of 0 dimension but only one value index of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#Get index 0 value of 0th dimension and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

### Pytorch tensors & Numpy
Numpy is a popular scientific Python numerical computing library
And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

#### Warning: when converting from Numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

In [ ]:
#Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Change the value of array,what will this do to 'tensor'
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
#Tensor to Numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor,what happens to 'numpy-tensor'?
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility(trying to take random out of random)
In short how a neural network learns:
* Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...
To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**
Essentially what random seed does is "flavour" the randomness

In [ ]:
torch.rand(3,3)

tensor([[0.4524, 0.7720, 0.8615],
        [0.5073, 0.6969, 0.6107],
        [0.1482, 0.2577, 0.1903]])

In [ ]:
import torch
#Create two random tensor
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8385, 0.4619, 0.7655, 0.5604],
        [0.2877, 0.0315, 0.4347, 0.0788],
        [0.7609, 0.8819, 0.4027, 0.6826]])
tensor([[0.6083, 0.1836, 0.3482, 0.2313],
        [0.4906, 0.2391, 0.1606, 0.8940],
        [0.0609, 0.3829, 0.9942, 0.1301]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#let's make some random but reproducible tensor
import torch
#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects ont the GPUs(and making faster computations)

GPUs= faster computation on numbers,thanks to CUDA+ NVIDIA hardware+ Pytorch working together behind the scenes to make everything hunky dori

### 1.Getting a GPU
1. Easiest- Use Google Colab for a free GPU(options to upgrade)
2. Use your own GPU- takes a little bit of setup and requires the investment of purchasing
https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing- GCP,AWS, Azure allow you to rent computers on the cloud and acess them.

### 2.Checking for GPU access with Pytorch

In [ ]:
#Check for GPU access with Pytorch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count the number of device
torch.cuda.device_count()

1

In [ ]:
!nvidia-smi

Sat Feb  8 18:39:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 3.Putting tensors(and models) on the GPU

The reason we want our tensorss/models on GPU is because using a GPU results in faster calculations

In [ ]:
#create a tensor(default on the CPU)
tensor=torch.tensor([1,2,2])
#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 2]) cpu


In [ ]:
#Move tensor to GPU(if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 2], device='cuda:0')

### 4.Moving tensors back to CPU

In [ ]:
#If tensor is on the GPU we cannot transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#To fix the GPU tensor with NumPy issue,we can first set it up to the cpu
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 2])