# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3,4])
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2],[2,1]])
# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[1,2,3],
              [1,2,3],[1,2,3]],
            [[1,2,3],[1,2,3],
             [1,2,3],[1,2,3]]])
a1,a2,a3

(array([1, 2, 3, 4]),
 array([[1, 2],
        [2, 1]]),
 array([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],
 
        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,type(a1)

((4,), 1, dtype('int32'), numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype,type(a2)

((2, 2), 2, dtype('int32'), numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype,type(a3)

((2, 4, 3), 3, dtype('int32'), numpy.ndarray)

In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

0  1
0  1  2
1  2  1

In [17]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[0, 3],
       [1, 9],
       [9, 0],
       [1, 1],
       [8, 4],
       [5, 0],
       [4, 2]])

In [31]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array1=np.random.random((3,5))
random_array1

array([[0.19204897, 0.88645645, 0.63565131, 0.01194629, 0.18347756],
       [0.68629836, 0.35039012, 0.78477802, 0.09669691, 0.89591175],
       [0.3106278 , 0.44316914, 0.61603932, 0.06069986, 0.7649514 ]])

In [34]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array2=np.random.rand(4,6)
random_array2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [39]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rarray=np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
rarray,np.unique(rarray)

(array([[9, 8, 2, 1, 7, 7, 8],
        [5, 3, 8, 6, 3, 1, 3],
        [5, 3, 1, 5, 7, 7, 9]]),
 array([1, 2, 3, 5, 6, 7, 8, 9]))

In [40]:
# Find the 0'th index of the latest array you created
rarray[0]

array([9, 8, 2, 1, 7, 7, 8])

In [41]:
# Get the first 2 rows of latest array you created
rarray[:2]

array([[9, 8, 2, 1, 7, 7, 8],
       [5, 3, 8, 6, 3, 1, 3]])

In [42]:
# Get the first 2 values of the first 2 rows of the latest array
rarray[:2,:2]

array([[9, 8],
       [5, 3]])

In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(seed=0)
a4=np.random.randint(10,size=(3,5))
a5=np.ones((3,5))
a4,a5

(array([[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [48]:
# Add the two arrays together
a4+a5

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [49]:
# Create another array of ones of shape (5, 3)
a6=np.ones((5,3))
a6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# Try add the array of ones and the other most recent array together
a4+a6.T

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

When you try the last cell, it produces an error. Why do think this is?

Ans:It is because shape of both the arrays are different

How would you fix it?

Ans:by using the transpose function and also we can reshape it..

In [52]:
# Create another array of ones of shape (3, 5)
a7=np.ones((3,5))

In [53]:
# Subtract the new array of ones from the other most recent array
a4-a7

array([[ 4., -1.,  2.,  2.,  6.],
       [ 8.,  2.,  4.,  1.,  3.],
       [ 6.,  5.,  7.,  7.,  0.]])

In [54]:
# Multiply the ones array with the latest array
a4*a7

array([[5., 0., 3., 3., 7.],
       [9., 3., 5., 2., 4.],
       [7., 6., 8., 8., 1.]])

In [55]:
# Take the latest array to the power of 2 using '**'
a4**2

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [56]:
# Do the same thing with np.square()
np.square(a4)

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [57]:
# Find the mean of the latest array using np.mean()
np.mean(a4)

4.733333333333333

In [58]:
# Find the maximum of the latest array using np.max()
np.max(a4)

9

In [59]:
# Find the minimum of the latest array using np.min()
np.min(a4)

0

In [60]:
# Find the standard deviation of the latest array
np.std(a4)

2.6449112566503166

In [62]:
# Find the variance of the latest array
np.var(a4)

6.995555555555556

In [63]:
# Reshape the latest array to (3, 5, 1)
a4.reshape((3,5,1))

array([[[5],
        [0],
        [3],
        [3],
        [7]],

       [[9],
        [3],
        [5],
        [2],
        [4]],

       [[7],
        [6],
        [8],
        [8],
        [1]]])

In [64]:
# Transpose the latest array
a4.T

array([[5, 9, 7],
       [0, 3, 6],
       [3, 5, 8],
       [3, 2, 8],
       [7, 4, 1]])

What does the transpose do?

Exchanges the number of rows and coloumns

In [66]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(seed=0)
dot1=np.random.randint(10,size=(3,3))
dot2=np.random.randint(10,size=(3,2))
dot1,dot2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]]),
 array([[4, 7],
        [6, 8],
        [8, 1]]))

In [67]:
# Perform a dot product on the two newest arrays you created
dot1.dot(dot2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [68]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
m1=np.random.randint(10,size=(4,3))
m2=np.random.randint(10,size=(4,3))
m1,m2

(array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0]]),
 array([[3, 5, 0],
        [2, 3, 8],
        [1, 3, 3],
        [3, 7, 0]]))

In [69]:
# Perform a dot product on the two newest arrays you created
m1.dot(m2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [70]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
m1.dot(m2.T)

array([[ 53,  89,  48,  67],
       [ 29,  59,  26,  31],
       [ 67, 114,  60,  83],
       [ 27,  17,  13,  33]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [75]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar1=np.random.randint(10,size=(3,5))
ar2=np.random.randint(10,size=(3,5))
ar1,ar2

(array([[2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4],
        [3, 4, 4, 8, 4]]),
 array([[3, 7, 5, 5, 0],
        [1, 5, 9, 3, 0],
        [5, 0, 1, 2, 4]]))

In [76]:
# Compare the two arrays with '>'
ar1>ar2

array([[False, False, False, False,  True],
       [ True, False, False,  True,  True],
       [False,  True,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [77]:
# Compare the two arrays with '>='
ar1>=ar2

array([[False, False, False,  True,  True],
       [ True, False, False,  True,  True],
       [False,  True,  True,  True,  True]])

In [96]:
# Find which elements of the first array are greater than 7


In [97]:
# Which parts of each array are equal? (try using '==')
ar1==ar2

array([[False, False, False, False,  True],
       [False, False, False, False,  True],
       [False,  True, False, False, False]])

In [98]:
# Sort one of the arrays you just created in ascending order
np.sort(ar2)

array([[0, 3, 5, 5, 7],
       [0, 1, 3, 5, 9],
       [0, 1, 2, 4, 5]])

In [99]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar2)

array([[4, 0, 2, 3, 1],
       [4, 0, 3, 1, 2],
       [1, 2, 3, 4, 0]], dtype=int64)

In [100]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar2)

7

In [104]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar2)

4

In [106]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar2,axis=1)

array([1, 2, 0], dtype=int64)

In [107]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar2,axis=0)

array([1, 2, 2, 2, 0], dtype=int64)

In [111]:
# Create an array of normally distributed random numbers
aa=np.random.normal(size=(3,5))
aa

array([[ 0.48842647, -0.83833097,  0.38116374, -0.99090328,  1.01788005],
       [ 0.3415874 , -1.25088622,  0.92525075, -0.90478616,  1.84369153],
       [ 1.52550724, -1.44553558,  0.37716061, -0.07055723,  0.60415971]])

In [113]:
# Create an array with 10 evenly spaced numbers between 1 and 100
aa1=np.arange(1,100,10)
aa1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.